using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Json;

namespace lhc;

internal record ClassGeneratedInfo(
    ClassInfo mInfo,
    string mGeneratedFilepath,
    string mOriginalFilepath,
    string mParseFnName,
    string mSerializeFnName,
    string mEditorFnName
    );

internal static class HeaderGenerator {

    private static ConfigFile? mCfg;
    private static string? mRootDir;
    private static Dictionary<string, ClassGeneratedInfo> mComponents = new( );

    public static void Initialize( string root, ConfigFile config ) {

        mCfg = config;
        mRootDir = root;

    }

    public static void GenerateFile( string sourceFile, List<ClassInfo> components ) {

        if (!File.Exists( sourceFile )) { throw new Exception( $"File {sourceFile} doesn't exist" ); }
        if (mCfg == null) throw new Exception( "Header generator not initialized" );

        StringBuilder sb = new( );
        string generatedPath = Path.Combine(
            Path.GetDirectoryName( sourceFile )!,
            Path.GetFileNameWithoutExtension( sourceFile ) + ".generated.hpp"
        );

        GeneratePreamble( sb, sourceFile, new[] { GetPath( "scene_dep_manager_include" ) } );
        foreach (var comp in components) {

            string compName = GetClassName( comp );
            string parseFnSig = GetTemplate( "parse_fn_signature" );
            string parseFnName = parseFnSig.Substring( 0, parseFnSig.IndexOf( '(' ) );

            string editorFnSig = GetTemplate( "editor_fn_signature" );
            string editorFnName = editorFnSig.Substring( 0, editorFnSig.IndexOf( '(' ) );

            var generatedInfo = mComponents[compName] = new ClassGeneratedInfo(
                mInfo: comp,
                mGeneratedFilepath: generatedPath,
                mOriginalFilepath: sourceFile,
                mParseFnName: parseFnName.FormatWith( "ClassName", comp.mTypeName ),
                mSerializeFnName: "TO IMPLEMENT",
                mEditorFnName: editorFnName.FormatWith( "ClassName", comp.mTypeName )
                );

            ParseGenerator.GenerateParseFn( sb, comp );
            EditorGenerator.GenerateEditorFn( generatedInfo );
            generate_component_name_fn( sb, comp );

        }

        File.WriteAllText( generatedPath, sb.ToString( ) );

    }

    public static string FormatWith( this string template, Dictionary<string, string> values ) {
        string result = template;
        foreach (var pair in values) {
            result = result.Replace( $"{{{pair.Key}}}", pair.Value );
        }
        return result;
    }
    public static string FormatWith( this string template, string key, string value ) {
        return template.Replace( $"{{{key}}}", value );
    }

    public static void Finalize( ) {

        if (mCfg == null) throw new Exception( "Header generator not initialized" );

        StringBuilder sb = new( );

        ParseGenerator.Finalize( mRootDir!, mComponents );
        EditorGenerator.Finalize( mRootDir!, mComponents );

    }

    public static string GetPath( string key ) {
        return mCfg!.paths.TryGetValue( key, out var val )
            ? val
            : throw new Exception( $"Missing path key '{key}' in config.json" );
    }

    public static string GetTemplate( string key ) {
        return mCfg!.templates.TryGetValue( key, out var val )
            ? val
            : throw new Exception( $"Missing template key '{key}' in config.json" );
    }

    public static string GetDefault( string key ) {
        return mCfg!.defaults.TryGetValue( key, out var val )
            ? val
            : throw new Exception( $"Missing defaults key '{key}' in config.json" );
    }

    public static string GetClassName( ClassInfo info ) {
        string fallback = info.mTypeName.StartsWith( 'C' )
            ? info.mTypeName[1..].ToLower( ) : info.mTypeName.ToLower( );
        return info.mArgs.mDisplayName ?? fallback;
    }

    public static string GetFieldName( FieldInfo info ) {
        return info.mName.TrimStart( 'm' ).ToLower( );
    }

    public static string? TypeToInspector( string type ) {
        if (mCfg!.types.TryGetValue( type, out var value )) {
            return value.inspector;
        }
        return null;
    }

    public static string? TypeToReader( string type ) {
        if (mCfg!.types.TryGetValue( type, out var value )) {
            return value.reader;
        }
        return null;
    }

    public static void GeneratePreamble( StringBuilder sb, string? sourceFile, IEnumerable<string>? extraIncludes = null ) {

        sb.AppendLine( $"//========= Copyright (C) 2025-present 3zymek, MIT License ============//" );
        sb.AppendLine( $"//" );
        sb.AppendLine( $"// Auto-generated by Lumen Header Compiler (LHC)." );
        sb.AppendLine( $"// Repository: https://github.com/3zymek/Lumen-Header-Compiler" );
        sb.AppendLine( $"// Source: {Path.GetFileName( sourceFile )}" );
        sb.AppendLine( $"//" );
        sb.AppendLine( $"// DO NOT EDIT - changes will be overwritten on next build." );
        sb.AppendLine( $"//" );
        sb.AppendLine( $"//=============================================================================//" );
        sb.AppendLine( $"#pragma once" );
        if (sourceFile != null) sb.AppendLine( $"#include \"{Path.GetFileName( sourceFile )}\"" );
        if (extraIncludes != null) {
            foreach (var include in extraIncludes) {
                sb.AppendLine( $"#include \"{include.Replace( '\\', '/' )}\"" );
            }
        }
        sb.AppendLine( );

    }

    private static void generate_component_name_fn( StringBuilder sb, ClassInfo component ) {

        string compNameNamespace = GetTemplate( "component_get_name_namespace" );
        sb.AppendLine( $"namespace {compNameNamespace}" + " {\n" );

        sb.AppendLine( "\ttemplate<>" );
        sb.AppendLine(
            "\tinline " +
            GetTemplate( "component_get_name_return" ) +
            " " +
            GetTemplate( "component_get_name_signature" ).FormatWith( "ClassName", component.mTypeName ) +
            " {\n"
            );
        sb.AppendLine( $"\t\treturn \"{GetClassName( component )}\";\n" );
        sb.AppendLine( "\t}\n" );

        sb.AppendLine( "} " + $"// namespace {compNameNamespace}" );

    }

}
