using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Json;

namespace lhc;

internal record JsonProperty( string reader, string imgui );
internal record JsonRoot(
    Dictionary<string, string> paths,
    Dictionary<string, string> templates,
    Dictionary<string, JsonProperty> types
    );

internal record ClassGeneratedInfo(
    ClassInfo mInfo,
    string mGeneratedFilepath,
    string mParseFnName,
    string mSerializeFnName,
    string mEditorFnName
    );

internal static class HeaderGenerator {

    private static JsonRoot? mRoot;
    private static Dictionary<string, ClassGeneratedInfo> mComponents = new( );

    private static string mSceneManagerPath = "";

    public static void Initialize( string sceneDepMgrPath ) {

        string jsonContent = File.ReadAllText( $"{Path.Combine( AppContext.BaseDirectory, "config.json" )}" );

        mRoot = JsonSerializer.Deserialize<JsonRoot>( jsonContent ) ??
            throw new Exception( $"Failed to deserialize {Path.Combine( AppContext.BaseDirectory, "config.json" )}" );

        mSceneManagerPath = sceneDepMgrPath.Replace('\\', '/');

    }

    public static void GenerateFile( string sourceFile, List<ClassInfo> components ) {

        if (!File.Exists( sourceFile )) { throw new Exception( $"File {sourceFile} doesn't exist" ); }
        if (mRoot == null) throw new Exception( "Header generator not initialized" );

        StringBuilder sb = new( );
        string generatedPath = Path.Combine(
            Path.GetDirectoryName( sourceFile )!,
            Path.GetFileNameWithoutExtension( sourceFile ) + ".generated.hpp"
        );

        generate_preamble( sb, sourceFile );
        foreach (var comp in components) {

            string compName = comp.mName.StartsWith( 'C' ) ? comp.mName[1..].ToLower( ) : comp.mName.ToLower( );
            string parseFnSig = mRoot.templates["parse_fn_signature"]!;
            string parseFnName = parseFnSig.Substring( 0, parseFnSig.IndexOf( '(' ) );

            mComponents[compName] = new ClassGeneratedInfo(
                mInfo: comp,
                mGeneratedFilepath: generatedPath,
                mParseFnName: string.Format( parseFnName, comp.mName ),
                mSerializeFnName: "TO IMPLEMENT",
                mEditorFnName: "TO IMPLEMENT"
                );

            generate_parse_fn( sb, comp );

        }
        generate_postamble( sb );

        File.WriteAllText( generatedPath, sb.ToString( ) );

    }

    public static void Finalize( string outputDir ) {

        if (!File.Exists( outputDir )) throw new Exception( $"File {outputDir} doesn't exist" );
        if (mRoot == null) throw new Exception( "Header generator not initialized" );

        string outputPath = Path.Combine(
            Path.GetDirectoryName( outputDir )!,
            Path.GetFileNameWithoutExtension( outputDir ) + ".generated.hpp"
        );

        finalize_scene_dep_mgr( outputPath );

    }

    private static void finalize_scene_dep_mgr( string outputPath ) {

        StringBuilder sb = new( );

        generate_preamble( sb, null, mComponents.Values.Select( v => v.mGeneratedFilepath ).Distinct( ) );

        sb.Append( $"\tinline void {mRoot!.templates["parse_fn_registry"]} " );
        sb.AppendLine( "{" );

        foreach (var (key, val) in mComponents) {

            sb.AppendLine( $"\t\tmap[ HashStr(\"{val.mInfo.mArgs.mID ?? key}\") ] = {val.mParseFnName};" );

        }

        sb.AppendLine( "\t}\n" );
        sb.AppendLine( "}" );

        File.WriteAllText( outputPath, sb.ToString( ) );

    }

    private static string? type_to_reader( string type ) {

        if (mRoot!.types.TryGetValue( type, out var value )) {
            return value.reader;
        }

        return null;

    }

    private static void generate_preamble( StringBuilder sb, string? sourceFile, IEnumerable<string>? extraIncludes = null ) {

        sb.AppendLine( $"//========= Copyright (C) 2026 3zymek, MIT License ============//" );
        sb.AppendLine( $"//" );
        sb.AppendLine( $"// Auto-generated by Lumen Header Compiler (LHC)." );
        sb.AppendLine( $"// Repository: https://github.com/3zymek/Lumen-Header-Compiler" );
        sb.AppendLine( $"// Source: {Path.GetFileName( sourceFile )}" );
        sb.AppendLine( $"//" );
        sb.AppendLine( $"// DO NOT EDIT - changes will be overwritten on next build." );
        sb.AppendLine( $"//" );
        sb.AppendLine( $"//=============================================================================//" );
        sb.AppendLine( $"#pragma once" );
        if (sourceFile != null) sb.AppendLine( $"#include \"{Path.GetFileName( sourceFile )}\"" );
        sb.AppendLine( $"#include \"{mSceneManagerPath}\"" );

        if (extraIncludes != null) {
            foreach (var include in extraIncludes) {
                sb.AppendLine( $"#include \"{include.Replace( '\\', '/' )}\"" );
            }
        }

        sb.AppendLine( );
        sb.Append( $"namespace {mRoot!.paths["code_namespace"]}" );
        sb.AppendLine( " {" );
        sb.AppendLine( );

    }

    private static void generate_postamble( StringBuilder sb ) {
        sb.Append( "}" );
        sb.AppendLine( $" // namespace {mRoot!.paths["code_namespace"]}" );
    }

    private static void generate_parse_fn( StringBuilder sb, ClassInfo component ) {

        string compName = component.mName.StartsWith( 'C' ) ? component.mName[1..].ToLower( ) : component.mName.ToLower( );
        string componentAlias = mRoot!.templates["parse_fn_comp_name"]!;

        sb.Append( $"\tinline void {string.Format( mRoot.templates["parse_fn_signature"], component.mName )}" );
        sb.AppendLine( "{\n" );
        sb.AppendLine( $"\t\t{mRoot.templates["parse_fn_body_open"]}\n" );
        sb.AppendLine( $"\t\t{component.mName} {componentAlias}; \n" );
        sb.Append( $"\t\twhile( {mRoot.templates["parse_fn_while_expr"]} )" );
        sb.AppendLine( " {" );
        sb.Append( $"\t\t\tif( {mRoot.templates["parse_fn_token_check"]} )" );
        sb.AppendLine( "{" );

        for (int i = 0; i < component.mFields.Count; i++) {

            var field = component.mFields[i];
            string reader = type_to_reader( field.mType ) ??
                throw new Exception( $"Unknown type: '{field.mType}' in {component.mName}.{field.mName}" );

            string keyword = i == 0 ? "if" : "else if";
            string fieldName = field.mName.TrimStart( 'm' ).ToLower( );

            sb.AppendLine( $"\t\t\t\t{keyword}( detail::IsString( tokens, i, \"{fieldName}\" ) )" );
            sb.AppendLine( $"\t\t\t\t\t{string.Format( mRoot.templates["parse_fn_field"], componentAlias, field.mName, reader )}" );

        }

        sb.AppendLine( "\t\t\t}" );
        sb.AppendLine( "\t\t\ti++;" );
        sb.AppendLine( "\t\t}\n" );
        sb.AppendLine( $"\t\t{string.Format( mRoot.templates["parse_fn_add"], componentAlias )}\n" );
        sb.AppendLine( "\t}" );

    }

}
