using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Json;

namespace lhc;

internal record JsonProperty( string reader, string imgui );
internal record JsonRoot( 
    Dictionary<string, string> paths,
    Dictionary<string, string> templates,
    Dictionary<string, JsonProperty> types 
    );

internal static class HeaderGenerator {
      
    private static readonly JsonRoot mRoot;

    static HeaderGenerator( ) {
        
        string jsonContent = File.ReadAllText( $"{get_current_path( )}/config.json" );

        mRoot = JsonSerializer.Deserialize<JsonRoot>( jsonContent ) ??
            throw new Exception( $"Failed to deserialize {get_current_path( )}/config.json" );

    }

    public static void Generate( string sourceFile, List<ConponentInfo> components ) {

        if (!File.Exists( sourceFile )) {
            throw new Exception( $"File {sourceFile} doesn't exist" );
        }

        StringBuilder sb = new( );
        generate_preamble( ref sb, sourceFile );

        foreach (var comp in components) {

            generate_parse_fn( ref sb, comp );

        }

        generate_postamble( ref sb );

        File.WriteAllText( sourceFile + ".generated.hpp", sb.ToString( ) );

    }

    public static void Finalize(string sceneParserPath, List<ConponentInfo> components ) {

        if (!File.Exists( sceneParserPath )) {
            throw new Exception( $"File {sceneParserPath} doesn't exist" );
        }

        StringBuilder sb = new( );
        generate_preamble( ref sb, sceneParserPath );

        foreach(var )


    }

    private static string? type_to_reader( string type ) {

        if (mRoot.types.TryGetValue( type, out var value )) {
            return value.reader;
        }

        return null;

    }

    private static void generate_preamble( ref StringBuilder sb, string sourceFile ) {

        sb.AppendLine( $"//========= Copyright (C) 2026 3zymek, MIT License ============//" );
        sb.AppendLine( $"//" );
        sb.AppendLine( $"// Auto-generated by Lumen Header Compiler (LHC)." );
        sb.AppendLine( $"// Repository: https://github.com/3zymek/Lumen-Header-Compiler" );
        sb.AppendLine( $"// Source: {Path.GetFileName(sourceFile)}" );
        sb.AppendLine( $"//" );
        sb.AppendLine( $"// DO NOT EDIT - changes will be overwritten on next build." );
        sb.AppendLine( $"//" );
        sb.AppendLine( $"//=============================================================================//" );
        sb.AppendLine( $"#pragma once" );
        sb.AppendLine( $"#include \"modules/scene/format/scene_parser.hpp\"" );
        sb.AppendLine( );
        sb.AppendLine( "namespace lum::fmt::detail {" );
        sb.AppendLine( );

    }

    private static string? get_current_path( [CallerFilePath] string path = "" ) {
        return Path.GetDirectoryName( path );
    }
    private static void generate_postamble( ref StringBuilder sb ) {
        sb.Append( "}" );

        sb.AppendLine( $" // namespace {mRoot.paths["preamble_namespace"]}" );
    }

    private static void generate_parse_fn( ref StringBuilder sb, ConponentInfo component ) {

        string compName = component.mName.TrimStart( 'C' ).ToLower( );
        string componentAlias = mRoot.templates["parse_fn_comp_name"];

        sb.Append( $"\t{string.Format( mRoot.templates["parse_fn_signature"], component.mName )}" );
        sb.AppendLine( "{\n" );
        sb.AppendLine( $"\t\t{mRoot.templates["parse_fn_body_open"]}\n" );
        sb.AppendLine( $"\t\t{component.mName} {componentAlias}; \n" );
        sb.AppendLine( "\t\twhile( in_block( tokens, i ) ) {" );
        sb.AppendLine( "\t\t\tif( tokens[i].mType == TokenType::Parameter ) {" );

        for (int i = 0; i < component.mFields.Count; i++) {
            var field = component.mFields[i];
            string reader = type_to_reader( field.mType ) ?? throw new Exception( "Unknown type" );
            string keyword = i == 0 ? "if" : "else if";

            sb.AppendLine( $"\t\t\t\t{keyword}( detail::IsString( tokens, i, \"{field.mName}\" ) )" );
            sb.AppendLine( $"\t\t\t\t\t{string.Format(mRoot.templates["parse_fn_field"], componentAlias, field.mName, reader)}" );

        }

        sb.AppendLine( "\t\t\t}" );
        sb.AppendLine( "\t\t\ti++;" );
        sb.AppendLine( "\t\t}\n" );
        sb.AppendLine( $"\t\t{string.Format(mRoot.templates["parse_fn_add"], componentAlias)}\n" );
        sb.AppendLine( "\t}" );

    }

}
