using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace lhc;

internal static class HeaderGenerator {

    public static void Generate( string sourceFile, List<ConponentInfo> components ) {

        if (!File.Exists( sourceFile )) {
            throw new Exception( $"File {sourceFile} doesn't exist" );
        }

        StringBuilder sb = new( );
        generate_preamble( ref sb, sourceFile );

        foreach (var comp in components) {

            generate_parse_fn( ref sb, comp );

        }

        generate_postamble( ref sb );

        File.WriteAllText( sourceFile + ".generated.hpp", sb.ToString( ) );

    }

    private static string? type_to_reader( string type ) => type switch
    {
        "glm::vec3" => "detail::ReadVec3Parameter",
        "glm::vec2" => "detail::ReadVec2Parameter",
        "float32" => "detail::ReadFloatParameter",
        "int32" => "detail::ReadIntParameter",
        "bool" => "detail::ReadBoolParameter",
        "String" => "detail::ReadStringParameter",
        _ => null
    };

    private static void generate_preamble( ref StringBuilder sb, string sourceFile ) {

        sb.AppendLine( $"//========= Copyright (C) 2026 3zymek, MIT License ============//" );
        sb.AppendLine( $"//" );
        sb.AppendLine( $"// Auto-generated by Lumen Header Compiler (LHC)." );
        sb.AppendLine( $"// Repository: https://github.com/3zymek/Lumen-Header-Compiler" );
        sb.AppendLine( $"// Source: {sourceFile}" );
        sb.AppendLine( $"//" );
        sb.AppendLine( $"// DO NOT EDIT - changes will be overwritten on next build." );
        sb.AppendLine( $"//" );
        sb.AppendLine( $"//=============================================================================//" );
        sb.AppendLine( $"#pragma once" );
        sb.AppendLine( $"#include \"modules/scene/format/scene_parser.hpp\"" );
        sb.AppendLine( );
        sb.AppendLine( "namespace lum::fmt::detail {" );
        sb.AppendLine( );

    }

    private static void generate_postamble( ref StringBuilder sb ) {
        sb.AppendLine( "} // namespace lum::fmt::detail" );
    }

    private static void generate_parse_fn( ref StringBuilder sb, ConponentInfo component ) {

        string compName = component.mName.TrimStart( 'C' ).ToLower( );

        sb.Append( $"\tvoid Parse{component.mName}( std::vector<FToken>& tokens, int32& i, FParseContext& ctx ) " );
        sb.AppendLine( "{" );
        sb.AppendLine( "\t\tdetail::ExpectOpeningBracket(tokens, i );\n" );
        sb.AppendLine( $"\t\t{component.mName} comp; \n" );
        sb.AppendLine( "\t\twhile( in_block( tokens, i ) ) {" );
        sb.AppendLine( "\t\t\tif( tokens[i].mType == TokenType::Parameter ) {" );

        for (int i = 0; i < component.mFields.Count; i++) {
            var field = component.mFields[i];
            string reader = type_to_reader( field.mType ) ?? throw new Exception( "Unknown type" );
            string keyword = i == 0 ? "if" : "else if";

            sb.AppendLine( $"\t\t\t\t{keyword}( detail::IsString( tokens, i, \"{field.mName}\" ) )" );
            sb.AppendLine( $"\t\t\t\t\tcomp.{field.mName} = {reader}( tokens, i );" );

        }

        sb.AppendLine( "\t\t\t}" );
        sb.AppendLine( "\t\t\ti++;" );
        sb.AppendLine( "\t\t}\n" );
        sb.AppendLine( $"SceneParser::RegisterGeneratedComponent( compName, Parse{component.mName} );" );
        sb.AppendLine( $"\t\tctx.mScene.mEntityMgr.AddComponent( ctx.mEntity, comp );\n" );
        sb.AppendLine( "\t}" );

    }

}
