using System.Text;

namespace lhc;

internal record ClassGeneratedInfo(
    ClassInfo mInfo,
    string mGeneratedFilepath,
    string mOriginalFilepath,
    string mParseFnName,
    string mSerializeFnName,
    string mEditorFnName
    );

internal class LhcPipeline {

    private ConfigFile? mCfg;
    private string? mRootDir;
    private Dictionary<string, ClassGeneratedInfo> mComponents = new( );

    readonly Dictionary<string, IRegistry> mRegistries = new( );

    public void Initialize( string rootDir, ConfigFile config ) {

        mCfg = config;
        mRootDir = rootDir;

        mRegistries.Add( "parse_registry", new ParseRegistry( mCfg ) );

    }

    public void GenerateFile( string sourceFile, List<ClassInfo> classInfos ) {

        if (!File.Exists( sourceFile )) { throw new Exception( $"File {sourceFile} doesn't exist" ); }
        if (mCfg == null) throw new Exception( "Header generator not initialized" );

        StringBuilder sb = new( );
        string generatedPath = Path.Combine(
            Path.GetDirectoryName( sourceFile )!,
            Path.GetFileNameWithoutExtension( sourceFile ) + ".generated.hpp"
        );

        GeneratePreamble( sb, sourceFile, new[] { mCfg.GetPath( "scene_dep_manager_include" ) } );
        foreach (var info in classInfos) {

            string compName = info.ResolveParseName();
            string parseFnSig = mCfg.GetTemplate( "parse_fn_signature" );
            string parseFnName = parseFnSig.Substring( 0, parseFnSig.IndexOf( '(' ) );

            string editorFnSig = mCfg.GetTemplate( "editor_fn_signature" );
            string editorFnName = editorFnSig.Substring( 0, editorFnSig.IndexOf( '(' ) );

            var generatedInfo = mComponents[compName] = new ClassGeneratedInfo(
                mInfo: info,
                mGeneratedFilepath: generatedPath,
                mOriginalFilepath: sourceFile,
                mParseFnName: parseFnName.FormatWith( "ClassName", info.mTypeName ),
                mSerializeFnName: "TO IMPLEMENT",
                mEditorFnName: editorFnName.FormatWith( "ClassName", info.mTypeName )
                );

            //ParseRegistry.GenerateParseFn( sb, info );
            //EditorRegistry.GenerateEditorFn( generatedInfo );

            GenerateNameGetterArgs args = new( );
            args.mSignature = mCfg.GetTemplate( "get_parse_name_signature" );
            args.mNamespace = mCfg.GetTemplate( "get_parse_name_namespace" );
            args.mReturnType = mCfg.GetTemplate( "get_parse_name_return" );
            args.mReturnVal = info.ResolveParseName();
            generate_name_getter_fn( sb, info, args );

            args.mSignature = mCfg.GetTemplate( "get_display_name_signature" );
            args.mNamespace = mCfg.GetTemplate( "get_display_name_namespace" );
            args.mReturnType = mCfg.GetTemplate( "get_display_name_return" );
            args.mReturnVal = info.ResolveDisplayName();
            generate_name_getter_fn( sb, info, args );

            args.mSignature = mCfg.GetTemplate( "get_category_name_signature" );
            args.mNamespace = mCfg.GetTemplate( "get_category_name_namespace" );
            args.mReturnType = mCfg.GetTemplate( "get_category_name_return" );
            args.mReturnVal = info.mArgs.mCategoryName ?? mCfg.GetDefault( "category" );
            generate_name_getter_fn( sb, info, args );

        }

        File.WriteAllText( generatedPath, sb.ToString( ) );

    }

    public void Finalize( ) {

        if (mCfg == null) throw new Exception( "Header generator not initialized" );

        StringBuilder sb = new( );

        foreach (var output in mCfg!.outputs) {

            switch (output.generator_type) {

                case "parse_registry":
                    //ParseRegistry.Finalize( mRootDir!, mComponents, output );
                    break;

                case "editor_registry":
                    //EditorRegistry.Finalize( mRootDir!, mComponents, output );
                    break;

            }

        }

    }

    public void GeneratePreamble( StringBuilder sb, string? sourceFile, IEnumerable<string>? extraIncludes = null ) {

        sb.AppendLine( $"//========= Copyright (C) 2025-present 3zymek, MIT License ============//" );
        sb.AppendLine( $"//" );
        sb.AppendLine( $"// Auto-generated by Lumen Header Compiler (LHC)." );
        sb.AppendLine( $"// Repository: https://github.com/3zymek/Lumen-Header-Compiler" );
        sb.AppendLine( $"// Source: {Path.GetFileName( sourceFile )}" );
        sb.AppendLine( $"//" );
        sb.AppendLine( $"// DO NOT EDIT - changes will be overwritten on next build." );
        sb.AppendLine( $"//" );
        sb.AppendLine( $"//=============================================================================//" );
        sb.AppendLine( $"#pragma once" );
        if (sourceFile != null) sb.AppendLine( $"#include \"{Path.GetFileName( sourceFile )}\"" );
        if (extraIncludes != null) {
            foreach (var include in extraIncludes) {
                sb.AppendLine( $"#include \"{include.Replace( '\\', '/' )}\"" );
            }
        }
        sb.AppendLine( );

    }

    private struct GenerateNameGetterArgs {

        public string mNamespace;
        public string mReturnType;
        public string mSignature;
        public string mReturnVal;

    }

    private void generate_name_getter_fn( StringBuilder sb, ClassInfo info, GenerateNameGetterArgs args ) {

        sb.AppendLine( $"namespace {args.mNamespace}" + " {\n" );
        sb.AppendLine( "\ttemplate<>" );
        sb.AppendLine(
            "\tinline " +
            args.mReturnType +
            " " +
            args.mSignature.FormatWith( "ClassName", info.mTypeName ) +
            " {"
            );
        sb.AppendLine( $"\t\treturn \"{args.mReturnVal}\";" );
        sb.AppendLine( "\t}\n" );
        sb.AppendLine( "} " + $"// namespace {args.mNamespace}" );

    }

}
